# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-11 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041a\u0430\u0442\u0430\u043b\u043e\u0433')),
            ],
        ),
        migrations.CreateModel(
            name='CatItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opt1_typ', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0422\u0438\u043f \u0442\u043e\u0432\u0430\u0440\u0430')),
                ('opt2_spec', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0412\u0438\u0434 \u0442\u043e\u0432\u0430\u0440\u0430')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Category', verbose_name='\u041a\u0430\u0442\u0430\u043b\u043e\u0433')),
                ('opt3_brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Brand', verbose_name='\u0411\u0440\u0435\u043d\u0434')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=254, upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0410\u043a\u0446\u0438\u043e\u043d\u043d\u044b\u0439 \u043f\u0430\u043a\u0435\u0442')),
            ],
        ),
        migrations.CreateModel(
            name='PackageItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default='0.0', max_digits=6, verbose_name='\u0426\u0435\u043d\u0430 \u0432 \u043f\u0430\u043a\u0435\u0442\u0435')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0412\u0438\u0434 \u0442\u043e\u0432\u0430\u0440\u0430')),
                ('file1', models.FileField(max_length=254, upload_to='file1')),
                ('file2', models.FileField(max_length=254, upload_to='file1')),
                ('rate', models.DecimalField(decimal_places=1, default='2.5', max_digits=2, verbose_name='\u0420\u0435\u0439\u0442\u0438\u043d\u0433')),
                ('price', models.DecimalField(decimal_places=2, default='0.0', max_digits=6, verbose_name='\u0426\u0435\u043d\u0430')),
                ('is_discont', models.NullBooleanField(verbose_name='\u0410\u043a\u0446\u0438\u043e\u043d\u043d\u044b\u0439')),
                ('ext_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='KeyWords')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Desciption')),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.CatItem', verbose_name='\u041a\u0430\u0442\u0430\u043b\u043e\u0433')),
            ],
        ),
        migrations.AddField(
            model_name='packageitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product', verbose_name='\u041f\u0440\u043e\u0434\u0443\u043a\u0442'),
        ),
        migrations.AddField(
            model_name='image',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product', verbose_name='\u041f\u0440\u043e\u0434\u0443\u043a\u0442'),
        ),
    ]
