# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-14 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20161214_1038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Brand', 'verbose_name_plural': 'Brand-\u044b'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '\u041a\u0430\u0442\u0430\u043b\u043e\u0433', 'verbose_name_plural': '\u041a\u0430\u0442\u0430\u043b\u043e\u0433\u0438'},
        ),
        migrations.AlterModelOptions(
            name='catitem',
            options={'verbose_name': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f \u043a\u0430\u0442\u0430\u043b\u043e\u0433\u0430', 'verbose_name_plural': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438 \u043a\u0430\u0442\u0430\u043b\u043e\u0433\u0430'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': '\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430', 'verbose_name_plural': '\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0438'},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'verbose_name': '\u0410\u043a\u0446\u0438\u043e\u043d\u043d\u044b\u0439 \u043f\u0430\u043a\u0435\u0442', 'verbose_name_plural': '\u0410\u043a\u0446\u0438\u043e\u043d\u043d\u044b\u0439 \u043f\u0430\u043a\u0435\u0442\u044b'},
        ),
        migrations.AlterModelOptions(
            name='packageitem',
            options={'verbose_name': '\u041f\u043e\u0437\u0438\u0446\u0438\u044f \u0432 \u0430\u043a\u0446\u0438\u043e\u043d\u043d\u043e\u043c \u043f\u0430\u043a\u0435\u0442\u0435', 'verbose_name_plural': '\u041f\u043e\u0437\u0438\u0446\u0438\u0438 \u0432 \u0430\u043a\u0446\u0438\u043e\u043d\u043d\u043e\u043c \u043f\u0430\u043a\u0435\u0442\u0435'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '\u0422\u043e\u0432\u0430\u0440', 'verbose_name_plural': '\u0422\u043e\u0432\u0430\u0440\u044b'},
        ),
        migrations.RemoveField(
            model_name='catitem',
            name='catalog',
        ),
        migrations.AlterField(
            model_name='catitem',
            name='opt1_typ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Category', verbose_name='\u041a\u0430\u0442\u0430\u043b\u043e\u0433'),
        ),
        migrations.AlterField(
            model_name='package',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ext_desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0414\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='product',
            name='file1',
            field=models.FileField(max_length=254, upload_to='file1', verbose_name='\u0421\u043f\u0435\u0446\u0438\u0444\u0438\u043a\u0430\u0446\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='product',
            name='file2',
            field=models.FileField(max_length=254, upload_to='file1', verbose_name='\u041a\u0430\u0442\u0430\u043b\u043e\u0433 pdf'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0442\u043e\u0432\u0430\u0440\u0430'),
        ),
    ]
