# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-16 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_chanel_content_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='chanel',
            name='ext_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='out_id'),
        ),
    ]
