# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-23 04:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_product_full_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d')),
                ('fio', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0424\u0418\u041e')),
                ('full_desc', models.TextField(blank=True, null=True, verbose_name='\u043f\u043e\u043b\u043d\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('status', models.CharField(choices=[('created', '\u0444\u043e\u0440\u043c\u0438\u0440\u0443\u0435\u0442\u0441\u044f'), ('processing', '\u0437\u0430\u043f\u0440\u043e\u0448\u0435\u043d'), ('in_work', '\u0432 \u0440\u0430\u0431\u043e\u0442\u0435'), ('sended', '\u043e\u0442\u043f\u0440\u0430\u0432\u043b\u0435\u043d'), ('received', '\u043f\u043e\u043b\u0443\u0447\u0435\u043d')], default='created', max_length=40, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
                ('count', models.IntegerField(verbose_name='\u041a\u043e\u043b-\u0432\u043e \u043f\u043e\u0437\u0438\u0446\u0438\u0439')),
            ],
            options={
                'verbose_name': '\u041a\u043e\u0440\u0437\u0438\u043d',
                'verbose_name_plural': '\u041a\u043e\u0440\u0437\u0438\u043d\u044b',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, verbose_name='\u041a\u043e\u043b-\u0432\u043e \u043f\u043e\u0437\u0438\u0446\u0438\u0439')),
                ('price', models.DecimalField(decimal_places=2, default='0.0', max_digits=6, verbose_name='\u0426\u0435\u043d\u0430')),
                ('is_package', models.BooleanField(verbose_name='\u041f\u0430\u043a\u0435\u0442\u043d\u044b\u0439')),
                ('package', models.IntegerField(blank=True, null=True, verbose_name='\u041f\u0430\u043a\u0435\u0442')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Cart', verbose_name='\u043a\u043e\u0440\u0437\u0438\u043d\u0430')),
            ],
            options={
                'verbose_name': '\u043f\u043e\u0437\u0438\u0446\u0438\u044f \u0432 \u041a\u043e\u0440\u0437\u0438\u043d\u0435',
                'verbose_name_plural': '\u043f\u043e\u0437\u0438\u0446\u0438\u0438 \u0432 \u041a\u043e\u0440\u0437\u0438\u043d\u0435',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='file2',
            field=models.FileField(max_length=254, upload_to='file2', verbose_name='\u041a\u0430\u0442\u0430\u043b\u043e\u0433 pdf'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product', verbose_name='\u0422\u043e\u0432\u0430\u0440'),
        ),
    ]
