# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-27 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20170126_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of adding')),
                ('name', models.EmailField(max_length=254, verbose_name='\u0418\u043c\u044f')),
                ('contact', models.CharField(max_length=255, verbose_name='\u041a\u043e\u043d\u0442\u0430\u043a\u0442')),
                ('question', models.TextField(blank=True, null=True, verbose_name='\u0421\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0435')),
            ],
        ),
        migrations.AlterField(
            model_name='content',
            name='ordering',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='ordering'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rate',
            field=models.IntegerField(default=3, verbose_name='\u0420\u0435\u0439\u0442\u0438\u043d\u0433'),
        ),
    ]
