# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-27 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20170127_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file1',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to='file1', verbose_name='\u0421\u043f\u0435\u0446\u0438\u0444\u0438\u043a\u0430\u0446\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='product',
            name='file2',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to='file2', verbose_name='\u041a\u0430\u0442\u0430\u043b\u043e\u0433 pdf'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rate',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=6, verbose_name='\u0420\u0435\u0439\u0442\u0438\u043d\u0433'),
        ),
    ]
